# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostname', models.CharField(max_length=120, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d\xe7\xa7\xb0')),
                ('ipadd_internet', models.CharField(max_length=120, verbose_name=b'\xe5\x85\xac\xe7\xbd\x91IP')),
                ('ipadd_internal', models.CharField(max_length=120, verbose_name=b'\xe5\x86\x85\xe7\xbd\x91IP')),
                ('status', models.CharField(default=b'Running', max_length=20, verbose_name=b'\xe7\x8a\xb6\xe6\x80\x81')),
                ('zone', models.CharField(max_length=120, verbose_name=b'\xe5\x8f\xaf\xe7\x94\xa8\xe5\x8c\xba')),
                ('os_name', models.CharField(max_length=120, verbose_name=b'\xe7\xb3\xbb\xe7\xbb\x9f\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('config', models.CharField(max_length=300, verbose_name=b'\xe7\xa1\xac\xe4\xbb\xb6\xe9\x85\x8d\xe7\xbd\xae')),
                ('time_created', models.DateTimeField(verbose_name=b'\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('time_release', models.DateTimeField(verbose_name=b'\xe6\x88\xaa\xe6\xad\xa2\xe6\x97\xb6\xe9\x97\xb4')),
                ('image_name', models.CharField(max_length=200)),
                ('instance_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
            ],
        ),
    ]
