# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=120, verbose_name=b'\xe5\xba\x94\xe7\x94\xa8\xe5\x90\x8d\xe7\xa7\xb0')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aliyun.Host')),
            ],
        ),
    ]
