# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='host',
        ),
        migrations.AddField(
            model_name='application',
            name='hosts',
            field=models.ManyToManyField(to='aliyun.Host'),
        ),
    ]
