# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliyun', '0003_auto_20170428_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('app_name',), 'verbose_name_plural': '\u5e94\u7528\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'ordering': ('hostname',), 'verbose_name_plural': '\u4e3b\u673a\u4fe1\u606f'},
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name=b'ssh\xe7\xab\xaf\xe5\x8f\xa3'),
        ),
    ]
