# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=120)),
                ('vm_ip', models.CharField(max_length=120)),
                ('apps_list', models.TextField(max_length=500)),
            ],
        ),
    ]
