# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='apps_list',
            field=models.CharField(max_length=500, verbose_name='APP列表'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vm_ip',
            field=models.CharField(max_length=120, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vm_name',
            field=models.CharField(max_length=120, verbose_name='主机名'),
        ),
    ]
