# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_auto_20170426_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='apps_list',
            field=models.CharField(max_length=500, verbose_name=b'APP\xe5\x88\x97\xe8\xa1\xa8'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vm_ip',
            field=models.CharField(max_length=120, verbose_name=b'IP\xe5\x9c\xb0\xe5\x9d\x80'),
        ),
        migrations.AlterField(
            model_name='host',
            name='vm_name',
            field=models.CharField(max_length=120, verbose_name=b'\xe4\xb8\xbb\xe6\x9c\xba\xe5\x90\x8d'),
        ),
    ]
